### ISSUE TITLE
how handle notifications?

### ISSUE THREAD

**Issue by nifist99** [marprin/laravel-midtrans#11]
how do I handle notifications or receive notifications after order ?, in the documentation I see no examples

**Comment by marprin** [comment]
Yes, inside the readme i haven't added it as the package only provide the function to get the status based on order_id. The way to handle the notification from Midtrans, you can refer to their [documentation](https://snap-docs.midtrans.com/#handling-notifications) for this moment. I'll try to add the way to handle notification from Midtrans later.

**Comment by marprin** [comment]
Hi, as i think i don't have much time to handle this and the official SDK has been provided by the company, i'll archive the repository. You can use https://github.com/Midtrans/midtrans-php.

I'll close the issue.

Thank you.
