### ISSUE TITLE
Support laravel 7

### ISSUE THREAD

**Issue by sunardo** [marprin/laravel-midtrans#15]
As you know, the latest laravel version laravel 7.
But when I install, it's error

$ composer require marprinhm/midtrans
Using version ^1.0 for marprinhm/midtrans
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v7.4.0
    - Conclusion: don't install laravel/framework v7.4.0

**Comment by marprin** [comment]
Hi,

previously i haven't upgraded the package to support Laravel 7. Now you can use it as normally.

[latest release version](https://github.com/marprin/laravel-midtrans/releases/tag/v1.0.1)
