### ISSUE TITLE
How I can use Core API (VT-Direct) ?

### ISSUE THREAD

**Issue by dyaskur** [marprin/laravel-midtrans#7]
In your doc only available Snap  and VT-Web, but how about Core API (VT-Direct) ?

**Comment by marprin** [comment]
Hi,

Yes, for this time, i just add the docs for Snap and VT-Web and actually for the VT-Direct there're only the function that you can use but for the parameters that you want to send, you can take a look on the midtrans documentation for this time. I'll try to update the docs as soon as possible.

For the midtrans documentation, you can have in [here](https://api-docs.midtrans.com/).

Thanks.
