### ISSUE TITLE
Dynamic CLIENT_KEY and SERVER_KEY to get snap token

### ISSUE THREAD

**Issue by kevinkjs** [marprin/laravel-midtrans#8]
Is it possible to get snap token with client and server key value dynamically? I need a function like this

`       
 $token = Midtrans::getSnapToken($transaction_data, $secret_key, $client_key);
`

**Comment by marprin** [comment]
Have you tried to set the variable on runtime @kjskjs ? So, you don't need to pass the key on get token as `getSnapToken` function only receive one parameter.
